-- Split the optional player's name into first and last name while preserving
-- existing registrations and keeping the columns in form order.

begin;

create table public.registrations_next (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  player_first_name text,
  player_last_name text,
  age smallint check (age is null or age between 1 and 120),
  programs text[] not null default '{}',
  locations text[] not null default '{}',
  message text
);

insert into public.registrations_next (
  id,
  created_at,
  first_name,
  last_name,
  email,
  phone,
  player_first_name,
  player_last_name,
  age,
  programs,
  locations,
  message
)
with source as (
  select
    registrations.*,
    to_jsonb(registrations) as row_data
  from public.registrations
),
normalized as (
  select
    source.*,
    coalesce(row_data ->> 'player', row_data ->> 'player_name', '') as full_player_name
  from source
)
select
  id,
  created_at,
  first_name,
  last_name,
  email,
  phone,
  coalesce(
    nullif(row_data ->> 'player_first_name', ''),
    substring(btrim(full_player_name) from '^\S+')
  ),
  coalesce(
    nullif(row_data ->> 'player_last_name', ''),
    nullif(btrim(regexp_replace(btrim(full_player_name), '^\S+\s*', '')), '')
  ),
  age,
  programs,
  locations,
  message
from normalized;

drop table public.registrations;
alter table public.registrations_next rename to registrations;

select setval(
  pg_get_serial_sequence('public.registrations', 'id'),
  coalesce(max(id), 1),
  max(id) is not null
)
from public.registrations;

alter table public.registrations enable row level security;
revoke all on table public.registrations from anon, authenticated;
grant all on table public.registrations to service_role;
revoke all on sequence public.registrations_next_id_seq from anon, authenticated;
grant usage, select on sequence public.registrations_next_id_seq to service_role;

commit;
