-- Rebuild registrations in the same order as the fields in signup.html.
-- Existing rows are preserved. The old full name is split at the first space:
-- the first word becomes first_name and the remainder becomes last_name.

begin;

create table public.registrations_clean (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  player text,
  age smallint check (age is null or age between 1 and 120),
  programs text[] not null default '{}',
  locations text[] not null default '{}',
  message text
);

insert into public.registrations_clean (
  id,
  created_at,
  first_name,
  last_name,
  email,
  phone,
  player,
  age,
  programs,
  locations,
  message
)
with source as (
  select
    registrations.*,
    to_jsonb(registrations) as row_data
  from public.registrations
),
normalized as (
  select
    source.*,
    coalesce(row_data ->> 'contact_name', row_data ->> 'name', '') as full_name
  from source
)
select
  id,
  created_at,
  coalesce(
    nullif(row_data ->> 'first_name', ''),
    substring(btrim(full_name) from '^\S+'),
    ''
  ),
  coalesce(
    row_data ->> 'last_name',
    btrim(regexp_replace(btrim(full_name), '^\S+\s*', '')),
    ''
  ),
  email,
  phone,
  coalesce(row_data ->> 'player', row_data ->> 'player_name'),
  nullif(coalesce(row_data ->> 'age', row_data ->> 'player_age'), '')::smallint,
  programs,
  case
    when row_data ? 'locations'
      then array(select jsonb_array_elements_text(row_data -> 'locations'))
    when row_data ? 'preferred_locations'
      then array(select jsonb_array_elements_text(row_data -> 'preferred_locations'))
    else '{}'::text[]
  end,
  message
from normalized;

drop table public.registrations;
alter table public.registrations_clean rename to registrations;

select setval(
  pg_get_serial_sequence('public.registrations', 'id'),
  coalesce(max(id), 1),
  max(id) is not null
)
from public.registrations;

-- The public website must not read or write this table directly. A later
-- server-side function can insert validated submissions while RLS stays on.
alter table public.registrations enable row level security;
revoke all on table public.registrations from anon, authenticated;
grant all on table public.registrations to service_role;

commit;
